version: "3.9"

services:
  pascalallen-nginx:
    build:
      context: ./etc/nginx
    container_name: pascalallen-nginx
    ports:
      - "80:80"
    env_file:
      - ./etc/nginx/nginx.env
    volumes:
      - .:/var/www/app:cached
    networks:
      - pascalallen_app_net

  pascalallen-fpm:
    build:
      context: ./etc/fpm
      args:
        PHP_INI_MODE: development
    environment:
      - LOG_STREAM=/tmp/stdout
    env_file:
      - ./.env
    volumes:
      - .:/var/www/app:cached
    networks:
      - pascalallen_app_net

  pascalallen-db:
    build:
      context: ./etc/db
    container_name: pascalallen-db
    ports:
      - 3307:3306
    env_file:
      - ./etc/db/db.env
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    networks:
      - pascalallen_app_net

networks:
  pascalallen_app_net:
    driver: bridge

volumes:
  db:
