version: "3.9"

services:
  dockersymfony-nginx:
    build:
      context: ./etc/nginx
    container_name: dockersymfony-nginx
    ports:
      - "80:80"
    env_file:
      - ./etc/nginx/nginx.env
    volumes:
      - .:/var/www/app:cached
    networks:
      - dockersymfony_app_net

  dockersymfony-fpm:
    build:
      context: ./etc/fpm
      args:
        PHP_INI_MODE: development
    environment:
      - LOG_STREAM=/tmp/stdout
    env_file:
      - ./.env
    volumes:
      - .:/var/www/app:cached
    networks:
      - dockersymfony_app_net

  dockersymfony-db:
    build:
      context: ./etc/db
    container_name: dockersymfony-db
    ports:
      - 3307:3306
    env_file:
      - ./etc/db/db.env
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    networks:
      - dockersymfony_app_net

networks:
  dockersymfony_app_net:
    driver: bridge

volumes:
  db:
